// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: pkg/pb/profile.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProfileManagementClient is the client API for ProfileManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProfileManagementClient interface {
	ViewProfile(ctx context.Context, in *ViewProfileRequest, opts ...grpc.CallOption) (*ViewProfileResponse, error)
}

type profileManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewProfileManagementClient(cc grpc.ClientConnInterface) ProfileManagementClient {
	return &profileManagementClient{cc}
}

func (c *profileManagementClient) ViewProfile(ctx context.Context, in *ViewProfileRequest, opts ...grpc.CallOption) (*ViewProfileResponse, error) {
	out := new(ViewProfileResponse)
	err := c.cc.Invoke(ctx, "/profile.ProfileManagement/ViewProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileManagementServer is the server API for ProfileManagement service.
// All implementations must embed UnimplementedProfileManagementServer
// for forward compatibility
type ProfileManagementServer interface {
	ViewProfile(context.Context, *ViewProfileRequest) (*ViewProfileResponse, error)
	mustEmbedUnimplementedProfileManagementServer()
}

// UnimplementedProfileManagementServer must be embedded to have forward compatible implementations.
type UnimplementedProfileManagementServer struct {
}

func (UnimplementedProfileManagementServer) ViewProfile(context.Context, *ViewProfileRequest) (*ViewProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewProfile not implemented")
}
func (UnimplementedProfileManagementServer) mustEmbedUnimplementedProfileManagementServer() {}

// UnsafeProfileManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProfileManagementServer will
// result in compilation errors.
type UnsafeProfileManagementServer interface {
	mustEmbedUnimplementedProfileManagementServer()
}

func RegisterProfileManagementServer(s grpc.ServiceRegistrar, srv ProfileManagementServer) {
	s.RegisterService(&ProfileManagement_ServiceDesc, srv)
}

func _ProfileManagement_ViewProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileManagementServer).ViewProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileManagement/ViewProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileManagementServer).ViewProfile(ctx, req.(*ViewProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProfileManagement_ServiceDesc is the grpc.ServiceDesc for ProfileManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProfileManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "profile.ProfileManagement",
	HandlerType: (*ProfileManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ViewProfile",
			Handler:    _ProfileManagement_ViewProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/pb/profile.proto",
}
